"""empty message

Revision ID: 1045068e15c1
Revises: 36236ddd09c0
Create Date: 2023-05-07 10:45:17.152710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1045068e15c1'
down_revision = '36236ddd09c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apitoken', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['apitoken'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('apitoken')

    # ### end Alembic commands ###
